name: RoadRunner Action

on:
  push:
    branches:
      - develop


jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: backend
        run: pip install -r requirements.txt


  run-tests:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Reinstall dependencies (if needed)
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Run tests with pytest
        working-directory: backend
        run: pytest

  run-pylint:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2


    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'


    - name: Install dependencies
      working-directory: backend
      run: pip install -r requirements.txt


    - name: Run Pylint
      run: |
        pylint_output=$(pylint --max-line-length=100 --output-format=text $(git ls-files '*.py'))

        # Print the full pylint output for debugging purposes
        echo "$pylint_output"

        # Extract the score from the pylint output
        score=$(echo "$pylint_output" | grep -oP '\d+\.\d+(?=/10)' | tail -n 1)

        # Check if the score is less than 5 and fail the build if so
        if (( $(echo "$score < 5" | bc -l) )); then
          echo "Pylint score is too low: $score"
          exit 1  # Fail the build
        else
          echo "Pylint score is acceptable: $score"
          exit 0
        fi
      working-directory: backend